---
# tasks file for readarr / ubuntu


- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - sqlite3

- name: Creates readarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ readarr.user }}"
    group: "{{ readarr.group }}"
    mode: 0775
    recurse: yes
  loop:
    - /var/lib/readarr

- name: Download readarr
  get_url:
    url: "{{ readarr_dl_url }}"
    dest: /tmp/
    mode: '0644'
    owner: "{{ readarr.user }}"
    group: "{{ readarr.user }}"

- name: Unarchive readarr
  unarchive:
    src: /tmp/Readarr.develop.0.3.14.2358.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: "{{ readarr.user }}"
    group: "{{ readarr.user }}"

- name: set readarr systemd unit file
  copy:
    src: readarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644

- name: Start and enable readarr service
  systemd:
    name: readarr
    state: started
    enabled: true

- name: Set firewalld ports
  firewalld:
    port: "{{ firewall.rules.allow }}"
    permanent: true
    state: enabled

- name: Restart firewalld one time
  systemd:
    name: firewalld
    state: restarted
    enabled: true
