---

- name: It's not DNS
  file:
   path: "/etc/resolv.conf"
   state: absent

- name: There's no way it's DNS
  copy:
    src: resolv.conf
    dest: /run/systemd/resolve/resolv.conf
    owner: systemd-resolve
    group: systemd-resolve
    mode: '0644'

- name: It was DNS
  file:
    src: "/run/systemd/resolve/resolv.conf"
    dest: "/etc/resolv.conf"
    state: link