---
# tasks file for base-os

# apply base system updates
#- import_tasks: updates.yml

# Setup base packages for os
#- import_tasks: packages.yml

# Configure local dns
#- import_tasks: dns.yml

# install tailscale
- import_tasks: tailscale.yml