---
# tasks file for base-os

# apply base system updates
- include_tasks: updates.yml

# Setup base packages for os
- include_tasks: packages.yml

# Configure local dns - moving over to dns server
#- include_tasks: dns.yml

# install tailscale
#- include_tasks: tailscale.yml
