---
- name: Debian | Apt Dependencies
  apt:
    name: "{{ tailscale_apt_dependencies }}"
    cache_valid_time: 3600
    state: present

- name: Debian | Add Tailscale Signing Key
  get_url:
    url: "{{ tailscale_apt_signkey }}"
    dest: "{{ tailscale_apt_keyring_path }}"
    mode: '0644'

- name: Debian | Add Tailscale Deb
  apt_repository:
    repo: "{{ tailscale_apt_deb }}"
    state: present

- name: Debian | Install Tailscale
  apt:
    name: "{{ tailscale_package }}"
    cache_valid_time: 3600
    state: '{{ state }}'