---

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

# fix the error Failed to connect to https://changelogs.ubuntu.com/meta-release-lts
- name: Reinstall ubuntu-release-upgrader-core
  apt:
    name: ubuntu-release-upgrader-core
    state: present
    force: yes
    update_cache: yes