---
# tasks file for users

# setup ssh to move around (bad juan)
- import_tasks: juan-ssh.yml

# create user
- import_tasks: plex-user.yml

# create user
- import_tasks: sonarr-user.yml

# create user
- import_tasks: radarr-user.yml

# create user
- import_tasks: lidarr-user.yml

# create user
- import_tasks: readarr-user.yml

# create user
- import_tasks: whisparr-user.yml

# create user
- import_tasks: prowlarr-user.yml

# create user
- import_tasks: transmission-user.yml