---
# tasks file for users

# setup ssh to move around (bad juan)
- include_tasks: juan-ssh.yml

# create user
- include_tasks: plex-user.yml

# create user
- include_tasks: sonarr-user.yml

# create user
- include_tasks: radarr-user.yml

# create user
- include_tasks: lidarr-user.yml

# create user
- include_tasks: readarr-user.yml

# create user
- include_tasks: whisparr-user.yml

# create user
- include_tasks: prowlarr-user.yml

# create user
- include_tasks: transmission-user.yml

# create user
- include_tasks: docker-user.yml
  tags: docker