---

- name: Create group "{{ plex.group }}"
  group:
    name: "{{ plex.group }}"
    state: present
    gid: "{{ plex.userid }}"

- name: Create user "{{ plex.user }}"
  user:
    name: "{{ plex.user }}"
    comment: "account for plex service"  
    create_home: yes
    shell: /bin/false
    group: "{{ plex.group }}"
    groups: "{{ plex.group }}"
    append: yes
    uid: "{{ plex.groupid }}"