---

- name: Create group "{{ transmission.group }}"
  group:
    name: "{{ transmission.group }}"
    state: present
    gid: "{{ transmission.userid }}"

- name: Create user "{{ transmission.user }}"
  user:
    name: "{{ transmission.user }}"
    comment: "account for transmission service"  
    create_home: yes
    shell: /bin/false
    group: "{{ transmission.group }}"
    groups: "{{ transmission.group }}"
    append: yes
    uid: "{{ transmission.groupid }}"