---
# tasks file for sonarr / ubuntu


- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - sqlite3

- name: Creates sonarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonarr.user }}"
    group: "{{ sonarr.group }}"
    mode: 0775
    recurse: yes
  loop:
    - /var/lib/Sonarr

- name: Download sonarr
  get_url:
    url: https://github.com/Sonarr/Sonarr/releases/download/v4.0.0.748/Sonarr.main.4.0.0.748.linux-x64.tar.gz
    dest: /tmp/
    mode: '0644'
    owner: "{{ sonarr.user }}"
    group: "{{ sonarr.user }}"

- name: Unarchive sonarr
  unarchive:
    src: /tmp/Sonarr.main.4.0.0.748.linux-x64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: "{{ sonarr.user }}"
    group: "{{ sonarr.user }}"

- name: set sonarr systemd unit file
  copy:
    src: sonarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644

- name: Start and enable sonarr service
  systemd:
    name: sonarr
    state: started
    enabled: true

- name: Set firewalld ports
  firewalld:
    port: 8989/tcp
    permanent: true
    state: enabled

- name: Restart firewalld one time
  systemd:
    name: firewalld
    state: restarted
    enabled: true
