---
# tasks file for adguard-server

- name: Creates resolved dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adguard.user }}"
    group: "{{ adguard.group }}"
    mode: 0775
    recurse: yes
  loop:
    - /etc/systemd/resolved.conf.d

- name: Copy adguardhome.conf file, backing if it diff
  copy:
    src: adguardhome.conf
    dest: /etc/systemd/resolved.conf.d/adguardhome.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: restart service dns, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-resolved





