---
# tasks file for adguard-server

- name: Creates adguard directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adguard.user }}"
    group: "{{ adguard.group }}"
    mode: 0775
    recurse: yes
  loop:
    - /opt/AdGuardHome

- name: Download adguard
  get_url:
    url: "{{ adguard_dl_url }}"
    dest: /tmp/
    mode: '0644'
    owner: "{{ adguard.user }}"
    group: "{{ adguard.user }}"

- name: Unarchive adguard
  unarchive:
    src: /tmp/AdGuardHome_linux_amd64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: "{{ adguard.user }}"
    group: "{{ adguard.user }}"

- name: set adguard systemd unit file
  copy:
    src: AdGuardHome.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644

- name: Start and enable adguard service
  systemd:
    name: AdGuardHome
    state: started
    enabled: true

- name: Set firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ firewall.rules.allow }}"

- name: Restart firewalld one time
  systemd:
    name: firewalld
    state: restarted
    enabled: true
