---
# tasks file for prowlarr / ubuntu


- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - sqlite3

- name: Creates prowlarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prowlarr.user }}"
    group: "{{ prowlarr.group }}"
    mode: 0775
    recurse: yes
  loop:
    - /var/lib/prowlarr

- name: Download prowlarr
  get_url:
    url: http://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
    dest: /tmp/
    mode: '0644'
    owner: "{{ prowlarr.user }}"
    group: "{{ prowlarr.user }}"

- name: Unarchive prowlarr
  unarchive:
    src: /tmp/Prowlarr.master.1.11.4.4173.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: "{{ prowlarr.user }}"
    group: "{{ prowlarr.user }}"

- name: set prowlarr systemd unit file
  copy:
    src: prowlarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644

- name: Start and enable prowlarr service
  systemd:
    name: prowlarr
    state: started
    enabled: true

- name: Set firewalld ports
  firewalld:
    port: 9696/tcp
    permanent: true
    state: enabled

- name: Restart firewalld one time
  systemd:
    name: firewalld
    state: restarted
    enabled: true
