---
# tasks file for plex / ubuntu

- name: Create group
  group:
    name: "{{ plex.group }}"
    state: present

- name: Create user
  user:
    name: "{{ plex.user }}"
    comment: "account for plex service"  
    create_home: yes
    shell: /bin/false
    group: "{{ plex.group }}"
    groups: "{{ plex.group }}"
    append: yes

- name: Creates media directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    mode: 0775
    recurse: yes
  loop:
    - /opt/plex/media
    - /opt/plex/media/series
    - /opt/plex/media/movies
    - /opt/plex/media/music

- name: Configure Plex repository
  apt_repository:
    repo: "{{ plex_repo_url }}"
    state: present
    update_cache: false
  register: status_plex_repo

- name: Install Plex Server
  apt:
    name: plexmediaserver
    state: present
    update_cache: "{{ status_plex_repo.changed }}"

- name: Start and enable Plex service
  systemd:
    name: plexmediaserver
    state: started
    enabled: true