---
# defaults file for base-os

packages:
  - firewalld
  - vim
  - htop
  - tree
  - net-tools
  - iostat

# tailscale clean up
release_stability: stable
state: latest

tailscale_package: tailscale
tailscale_service: tailscaled

tailscale_apt_dependencies:
  - gnupg2
  - gnupg-agent
  - apt-transport-https
  - python3-apt

tailscale_debian_distro:
  ubuntu: ubuntu

tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg

tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }} {{ ansible_distribution_release | lower }} main

tailscale_apt_signkey: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }}/{{ ansible_distribution_release | lower }}.noarmor.gpg