---
- name: Docker user bash config and completion
  become: true
  become_user: "{{ docker_user }}"
  block:
    - name: Add .bash_completion script
      copy:
        src: bash_completion
        dest: "{{ docker_user_home }}/.bash_completion"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0750"

    - name: Create user bash completion dir
      file:
        path: "{{ docker_user_home }}/.bash_completion.d"
        state: directory
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0750"

    - name: Install docker bash completion
      get_url:
        url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker
        dest: "{{ docker_user_home }}/.bash_completion.d/"
        checksum: sha256:{{ docker_bash_completion_shasum }}
        mode: "0644"

    - name: Extend Docker user bashrc config
      blockinfile:
        path: "{{ docker_user_home }}/.bashrc"
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0644"
        block: |
          export XDG_RUNTIME_DIR="/run/user/{{ docker_user_uid }}"
          export DOCKER_HOST="unix:///run/user/{{ docker_user_uid }}/docker.sock"
          export PATH="{{ docker_user_home }}/bin:{{ docker_user_home }}/.local/bin:$PATH"
