---

- name: Create directory for user service configuration
  file:
    path: "/etc/systemd/system/user@.service.d"
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Create delegate.conf file for user service
  copy:
    src: delegate.conf
    dest: "/etc/systemd/system/user@.service.d/delegate.conf"
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true