---
- name: Install required packages
  include_tasks: packages.yml
  tags: packages

- name: modprobe loads
  include_tasks: modprobe.yml
  tags: modprobe

- name: Configure sysctl
  include_tasks: sysctl.yml
  tags: sysctl

- name: Configure systemd resource management
  include_tasks: delegate.yml
  tags: delegate

- name: Install and configure Docker rootless
  include_tasks: rootless-docker.yml
  tags: rootless

- name: Install Docker Compose rootless
  include_tasks: rootless-compose.yml
  tags: compose

- name: Deploy bash aliases
  include_tasks: bash_aliases.yml

- name: Deploy bash completion
  include_tasks: bashrc.yml

- name: Configure data disk
  include_tasks: data-disk.yml
  tags: disk