---
- name: Install required packages
  import_tasks: packages.yml
  tags: packages

- name: modprobe loads
  import_tasks: modprobe.yml
  tags: modprobe

- name: Configure sysctl
  import_tasks: sysctl.yml
  tags: sysctl

- name: Configure systemd resource management
  import_tasks: delegate.yml
  tags: delegate

- name: Install and configure Docker rootless
  import_tasks: rootless-docker.yml
  tags: rootless

- name: Install Docker Compose rootless
  import_tasks: rootless-compose.yml
  tags: compose

- name: Deploy bash aliases
  import_tasks: bash_aliases.yml

- name: Deploy bash completion
  import_tasks: bashrc.yml

- name: Configure data disk
  import_tasks: data-disk.yml
  tags: disk