---

- name: Install rootless Docker compose
  become: true
  become_user: "{{ docker_user }}"
  block:
    - name: Stat Compose in /bin dir
      stat:
        path: "{{ docker_user_home }}/bin/docker-compose"
      register: docker_compose_bin

    - name: Create cli-plugins directory
      file:
        path: "{{ docker_user_home }}/.docker/cli-plugins"
        state: directory
        mode: "0700"

    - name: Download docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v{{ docker_compose_release }}/docker-compose-linux-x86_64
        dest: "{{ docker_user_home }}/.docker/cli-plugins/docker-compose"
        checksum: sha256:{{ docker_compose_release_shasum }}
        owner: "{{ docker_user }}"
        mode: "0755"
      when: docker_compose

    - name: Remove Compose in /bin dir
      file:
        path: "{{ docker_user_home }}/bin/docker-compose"
        state: absent
      when: docker_compose_bin.stat.exists and not docker_compose_bin.stat.islnk

    - name: Create Compose link
      file:
        src: "{{ docker_user_home }}/.docker/cli-plugins/docker-compose"
        dest: "{{ docker_user_home }}/bin/docker-compose"
        state: link
